In [3]:
names = ["john","paul","ringo","george"]

In [4]:
for i in names:
    print (i)
    if i == "ringo":
        break

john
paul
ringo


In [5]:
#loop macht 3er Schritte
for x in range (1,21,3):
    print (x)

1
4
7
10
13
16
19


In [6]:
#break befehl unterbricht loop
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    break
  print(x)

apple


In [7]:
#A nested loop is a loop inside a loop.
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, y) 

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry


In [8]:
#continue überspringt wert
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    continue
  print(x)


apple
cherry


In [9]:
#create list of 80 random elements with values 0-100
import random
sample_list_1=(random.sample(range(101), k=80))
print (sample_list_1)

[84, 33, 23, 1, 44, 66, 70, 38, 31, 36, 12, 89, 39, 69, 96, 21, 46, 63, 0, 13, 6, 100, 77, 8, 58, 93, 76, 29, 32, 56, 40, 90, 67, 24, 94, 49, 48, 64, 75, 54, 88, 28, 16, 78, 86, 22, 97, 19, 99, 53, 62, 18, 80, 20, 30, 37, 11, 74, 35, 3, 50, 61, 55, 68, 17, 95, 79, 98, 2, 83, 5, 87, 85, 57, 59, 15, 27, 34, 4, 60]


In [10]:
import random
random.randint(10, 11)

10

In [11]:
def hello_func():
    print("hello Function")

hello_func()
hello_func()
hello_func()
hello_func()

hello Function
hello Function
hello Function
hello Function


In [12]:
import random

def hello_func(greeting = "hi", name = "you") :
    return "{}, {}".format(greeting, name).upper()
    
print(hello_func())


HI, YOU


In [13]:
def student_info(*args, **kwargs):
    print(args)
    print(kwarg)

In [14]:
#dictonary key value pair
dict = {"cat": "meow", "cow":"mooh", "dog":"bark"}
x = dict["cat"]
print(x)

dict["bird"] ="zirp"
print(dict)

for k,v in dict.items():
    print(k+": "+v)

meow
{'cat': 'meow', 'cow': 'mooh', 'dog': 'bark', 'bird': 'zirp'}
cat: meow
cow: mooh
dog: bark
bird: zirp


In [15]:
myDict = {"name": "John", "country": "Norway"}
mySeparator = "TEST"

x = ", ".join(myDict.values())

print(x)


John, Norway


In [16]:
import numpy as np

In [17]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


In [18]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [20]:
message = 'How does this work?'
translated = '' #cipher text is stored in this variable
i = len(message) - 1

while i >= 0:
   translated = translated + message[i]
   i = i - 1
print('The cipher text is : ', translated)

The cipher text is :  ?krow siht seod woH


In [21]:
def encrypt(text,s):
result = ""
   # transverse the plain text
   for i in range(len(text)):
      char = text[i]
      # Encrypt uppercase characters in plain text
      
      if (char.isupper()):
         result += chr((ord(char) + s-65) % 26 + 65)
      # Encrypt lowercase characters in plain text
      else:
            result += chr((ord(char) + s - 97) % 26 + 97)
      return result
#check the above function
text = "CEASER CIPHER DEMO"
s = 4

print "Plain Text : " + text
print "Shift pattern : " + str(s)
print "Cipher: " + encrypt(text,s)

IndentationError: expected an indented block (<ipython-input-21-77fc53ce950e>, line 2)

In [ ]:
#list comprehnsion
square=
print(square)

In [23]:
import numpy as np

In [24]:
a=np.random.random((2,3))

In [25]:
a

array([[0.00711434, 0.01613151, 0.170539  ],
       [0.62967321, 0.43648852, 0.5433418 ]])

In [26]:
a.shape

(2, 3)

In [27]:
a.size #two by three items is 6

6

In [28]:
a[0, 0] # element links oben

0.0071143357237223315

In [29]:
a [:,0] #hole first column

array([0.00711434, 0.62967321])

In [30]:
a[0,:] #hole first row

array([0.00711434, 0.01613151, 0.170539  ])

In [31]:
np.random.random((2,3,5)) #3 dimensons: 2 depth / 3 columns / 5 rows

array([[[0.03474619, 0.6407788 , 0.79723381, 0.57268447, 0.51062382],
        [0.09640925, 0.30676413, 0.79504163, 0.55670414, 0.9285344 ],
        [0.67239878, 0.03020509, 0.32714086, 0.14975026, 0.86263021]],

       [[0.02909728, 0.81314075, 0.68681486, 0.02192829, 0.01769043],
        [0.25531275, 0.37218867, 0.8244451 , 0.62678242, 0.70772964],
        [0.56702296, 0.74600682, 0.32333266, 0.20127352, 0.93388457]]])

In [32]:
b=np.random.random((2,3,5))
b

array([[[0.3012421 , 0.50597416, 0.75989096, 0.97537364, 0.85513257],
        [0.73207502, 0.9797952 , 0.53746343, 0.76546102, 0.69817599],
        [0.12589537, 0.62258934, 0.95659582, 0.80897047, 0.0452021 ]],

       [[0.93392817, 0.0104043 , 0.22007246, 0.6270459 , 0.06877639],
        [0.30343447, 0.0244144 , 0.60235848, 0.15477219, 0.37802477],
        [0.78602222, 0.37841686, 0.28776075, 0.61531766, 0.72860003]]])

In [53]:
b*10 #smart way to have random numbers between 0 and 10 - 10 not included

array([[[3.01242102, 5.05974164, 7.59890955, 9.75373638, 8.5513257 ],
        [7.3207502 , 9.797952  , 5.37463428, 7.65461021, 6.98175993],
        [1.25895371, 6.22589341, 9.56595822, 8.0897047 , 0.452021  ]],

       [[9.33928168, 0.10404295, 2.20072462, 6.27045897, 0.68776394],
        [3.03434467, 0.244144  , 6.02358478, 1.54772186, 3.78024774],
        [7.86022217, 3.78416859, 2.8776075 , 6.15317663, 7.28600027]]])

In [33]:
b[0,0,0]

0.30124210222100367

In [34]:
b[0,2,:]#vorderste Matrix, komplette 3. Zeile,

array([0.12589537, 0.62258934, 0.95659582, 0.80897047, 0.0452021 ])

In [35]:
b[0,:,2]#vorderste Matrix komplette 3. Spalte

array([0.75989096, 0.53746343, 0.95659582])

In [36]:
#mutabe ich kann eine einzelne Zeile ändern
a[0,0,0]=5
a

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [37]:
#insert list into array
mylist=['cat','dog']
np.array(mylist)

array(['cat', 'dog'], dtype='<U3')

In [38]:
#DIFFRENCE nump.add" vs "+"

In [56]:
first=[1,2,3]
second=[4,5,6]
print(first+second) #joins two lists
print (np.add(first,second))#addiert Element für Element

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [ ]:
import numpy as np

In [39]:
atoms = np.array([[0., 0., 0.],
                  [3., 3., 3.],
                  [2., 8., 7.]]
                 )

In [40]:
atoms

array([[0., 0., 0.],
       [3., 3., 3.],
       [2., 8., 7.]])

In [41]:
masses = np.array([1., 1., 5.])

In [42]:
atoms = atoms + [1.,2.,3.]
atoms

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 3., 10., 10.]])

In [43]:
riddle = np.array([[ 533.,  502.,  530.,  591.,  552.,  563.,  508.,  581.,  570.,  557.,  510.,  303.,  355.,  389.,  306.,  598.,  540.,  526.,  585.,  599.,  505.,  547.,  569.,  566.,  580.,  564.,  531.,  573.],
       [ 512.,  522.,  540.,  510.,  541.,  544.,  521.,  567.,  324.,  388.,  384.,  495.,  457.,  469.,  485.,  300.,  426.,  410.,  584.,  545.,  518.,  591.,  518.,  536.,  508.,  556.,  595.,  560.],
       [ 545.,  584.,  521.,  552.,  589.,  583.,  314.,  301.,  461.,  473.,  436.,  469.,  478.,  440.,  449.,  431.,  461.,  461.,  322.,  319.,  592.,  522.,  554.,  569.,  593.,  502.,  551.,  514.],
       [ 576.,  517.,  538.,  588.,  550.,  331.,  529.,  532.,  470.,  469.,  471.,  461.,  426.,  400.,  450.,  462.,  422.,  430.,  454.,  487.,  398.,  529.,  584.,  567.,  594.,  522.,  530.,  506.],
       [ 542.,  582.,  520.,  525.,  319.,  575.,  543.,  481.,  413.,  474.,  408.,  446.,  433.,  465.,  409.,  448.,  407.,  401.,  485.,  434.,  403.,  360.,  525.,  523.,  581.,  528.,  555.,  567.],
       [ 533.,  588.,  569.,  383.,  581.,  541.,  558.,  448.,  411.,  425.,  403.,  463.,  423.,  457.,  493.,  472.,  460.,  470.,  444.,  418.,  498.,  426.,  340.,  577.,  556.,  544.,  560.,  589.],
       [ 576.,  552.,  550.,  365.,  587.,  543.,  575.,  586.,  425.,  430.,  493.,  488.,  446.,  460.,  447.,  493.,  404.,  414.,  444.,  430.,  417.,  449.,  317.,  538.,  559.,  596.,  513.,  553.],
       [ 567.,  574.,  374.,  513.,  578.,  593.,  539.,  555.,  512.,  407.,  435.,  483.,  458.,  456.,  462.,  433.,  497.,  465.,  459.,  400.,  445.,  436.,  456.,  356.,  547.,  526.,  508.,  573.],
       [ 537.,  515.,  398.,  576.,  525.,  530.,  529.,  584.,  544.,  513.,  450.,  420.,  426.,  489.,  441.,  432.,  427.,  444.,  482.,  415.,  486.,  472.,  466.,  320.,  501.,  535.,  592.,  580.],
       [ 539.,  542.,  304.,  522.,  565.,  500.,  559.,  530.,  554.,  520.,  526.,  594.,  423.,  472.,  477.,  468.,  428.,  374.,  343.,  332.,  379.,  419.,  477.,  354.,  557.,  554.,  554.,  550.],
       [ 544.,  383.,  567.,  520.,  575.,  372.,  393.,  528.,  546.,  571.,  531.,  538.,  548.,  540.,  566.,  355.,  387.,  407.,  471.,  332.,  352.,  347.,  369.,  494.,  394.,  566.,  590.,  521.],
       [ 590.,  326.,  524.,  327.,  357.,  501.,  559.,  348.,  566.,  516.,  522.,  505.,  502.,  501.,  363.,  445.,  442.,  398.,  329.,  548.,  591.,  512.,  595.,  358.,  344.,  571.,  519.,  543.],
       [ 571.,  362.,  322.,  544.,  251.,  223.,  523.,  544.,  355.,  542.,  597.,  587.,  571.,  322.,  446.,  377.,  343.,  108.,  509.,  573.,  136.,  584.,  672.,  367.,  349.,  564.,  543.,  520.],
       [ 585.,  312.,  225.,  228.,  435.,  484.,  215.,  536.,  336.,  522.,  529.,  557.,  375.,  455.,  350.,  371.,  108.,  523.,  507.,  218.,  298.,  221.,  292.,  244.,  242.,  294.,  556.,  573.],
       [ 552.,  232.,  444.,  458.,  454.,  435.,  234.,  564.,  503.,  365.,  589.,  555.,  303.,  394.,  582.,  364.,  507.,  258.,  299.,  258.,  219.,  291.,  269.,  269.,  243.,  230.,  281.,  536.],
       [ 279.,  522.,  453.,  406.,  419.,  487.,  444.,  514.,  283.,  398.,  521.,  352.,  487.,  309.,  347.,  108.,  214.,  236.,  602.,  261.,  221.,  200.,  292.,  235.,  261.,  236.,  292.,  540.],
       [ 227.,  460.,  430.,  405.,  451.,  108.,  544.,  454.,  409.,  379.,  505.,  595.,  314.,  317.,  325.,  108.,  236.,  279.,  270.,  234.,  226.,  553.,  215.,  219.,  246.,  622.,  540.,  577.],
       [ 595.,  218.,  209.,  456.,  108.,  584.,  549.,  576.,  450.,  401.,  491.,  515.,  321.,  654.,  697.,  267.,  276.,  249.,  531.,  651.,  606.,  558.,  604.,  693.,  594.,  570.,  560.,  523.],
       [ 524.,  564.,  433.,  400.,  108.,  516.,  575.,  413.,  662.,  648.,  666.,  470.,  579.,  488.,  641.,  210.,  204.,  553.,  541.,  648.,  238.,  656.,  230.,  642.,  549.,  599.,  598.,  500.],
       [ 524.,  596.,  549.,  439.,  108.,  108.,  437.,  691.,  693.,  671.,  659.,  628.,  420.,  494.,  581.,  282.,  246.,  506.,  611.,  612.,  227.,  670.,  275.,  691.,  634.,  461.,  597.,  553.],
       [ 573.,  577.,  595.,  436.,  468.,  108.,  479.,  679.,  686.,  686.,  678.,  627.,  435.,  586.,  515.,  297.,  264.,  263.,  679.,  648.,  521.,  570.,  609.,  601.,  687.,  481.,  574.,  509.],
       [ 501.,  544.,  508.,  539.,  430.,  499.,  108.,  474.,  656.,  669.,  601.,  462.,  108.,  108.,  108.,  502.,  232.,  685.,  687.,  201.,  437.,  569.,  549.,  576.,  558.,  409.,  516.,  584.],
       [ 527.,  515.,  584.,  581.,  505.,  411.,  462.,  489.,  465.,  454.,  406.,  108.,  108.,  347.,  307.,  262.,  576.,  580.,  282.,  262.,  240.,  295.,  276.,  210.,  214.,  280.,  277.,  509.],
       [ 537.,  562.,  565.,  573.,  559.,  500.,  466.,  464.,  410.,  404.,  108.,  108.,  108.,  108.,  108.,  287.,  543.,  521.,  686.,  659.,  261.,  278.,  266.,  276.,  293.,  288.,  554.,  541.],
       [ 586.,  596.,  509.,  579.,  530.,  508.,  579.,  480.,  439.,  629.,  631.,  458.,  488.,  416.,  429.,  477.,  487.,  535.,  564.,  546.,  538.,  529.,  596.,  412.,  500.,  559.,  508.,  596.],
       [ 536.,  578.,  502.,  522.,  531.,  525.,  587.,  580.,  501.,  487.,  439.,  432.,  478.,  443.,  405.,  548.,  533.,  439.,  486.,  415.,  476.,  417.,  472.,  541.,  528.,  595.,  531.,  549.],
       [ 548.,  562.,  550.,  561.,  584.,  598.,  572.,  584.,  581.,  544.,  577.,  591.,  548.,  530.,  512.,  552.,  587.,  511.,  577.,  565.,  591.,  560.,  565.,  595.,  544.,  556.,  585.,  520.]])

In [44]:
riddle

array([[533., 502., 530., 591., 552., 563., 508., 581., 570., 557., 510.,
        303., 355., 389., 306., 598., 540., 526., 585., 599., 505., 547.,
        569., 566., 580., 564., 531., 573.],
       [512., 522., 540., 510., 541., 544., 521., 567., 324., 388., 384.,
        495., 457., 469., 485., 300., 426., 410., 584., 545., 518., 591.,
        518., 536., 508., 556., 595., 560.],
       [545., 584., 521., 552., 589., 583., 314., 301., 461., 473., 436.,
        469., 478., 440., 449., 431., 461., 461., 322., 319., 592., 522.,
        554., 569., 593., 502., 551., 514.],
       [576., 517., 538., 588., 550., 331., 529., 532., 470., 469., 471.,
        461., 426., 400., 450., 462., 422., 430., 454., 487., 398., 529.,
        584., 567., 594., 522., 530., 506.],
       [542., 582., 520., 525., 319., 575., 543., 481., 413., 474., 408.,
        446., 433., 465., 409., 448., 407., 401., 485., 434., 403., 360.,
        525., 523., 581., 528., 555., 567.],
       [533., 588., 569., 383., 581

In [45]:
print(riddle.shape)
print(riddle.size)

(27, 28)
756


In [46]:
riddle[:,-1]

array([573., 560., 514., 506., 567., 589., 553., 573., 580., 550., 521.,
       543., 520., 573., 536., 540., 577., 523., 500., 553., 509., 584.,
       509., 541., 596., 549., 520.])

In [50]:
print(riddle)

[[533. 502. 530. 591. 552. 563. 508. 581. 570. 557. 510. 303. 355. 389.
  306. 598. 540. 526. 585. 599. 505. 547. 569. 566. 580. 564. 531. 573.]
 [512. 522. 540. 510. 541. 544. 521. 567. 324. 388. 384. 495. 457. 469.
  485. 300. 426. 410. 584. 545. 518. 591. 518. 536. 508. 556. 595. 560.]
 [545. 584. 521. 552. 589. 583. 314. 301. 461. 473. 436. 469. 478. 440.
  449. 431. 461. 461. 322. 319. 592. 522. 554. 569. 593. 502. 551. 514.]
 [576. 517. 538. 588. 550. 331. 529. 532. 470. 469. 471. 461. 426. 400.
  450. 462. 422. 430. 454. 487. 398. 529. 584. 567. 594. 522. 530. 506.]
 [542. 582. 520. 525. 319. 575. 543. 481. 413. 474. 408. 446. 433. 465.
  409. 448. 407. 401. 485. 434. 403. 360. 525. 523. 581. 528. 555. 567.]
 [533. 588. 569. 383. 581. 541. 558. 448. 411. 425. 403. 463. 423. 457.
  493. 472. 460. 470. 444. 418. 498. 426. 340. 577. 556. 544. 560. 589.]
 [576. 552. 550. 365. 587. 543. 575. 586. 425. 430. 493. 488. 446. 460.
  447. 493. 404. 414. 444. 430. 417. 449. 317. 538. 559. 5

In [58]:

for x in len(riddle): 
    if riddle[x] >=200 and  riddle[x]<= 300:
        riddle [x]=0
    elif riddle[x]>=300 and  riddle[x]<=400:
        riddle [x]=40
    elif riddle[x]>=400 and  riddle[x]<=500:
        riddle [x]=156
    elif riddle[x]>=500 and  riddle[x]<=600:
        riddle [x]=220
riddle

TypeError: 'int' object is not iterable

In [61]:
#PANDAS
#Series vs Data Frame
import pandas as pd
import numpy as np

In [74]:
#SERIES
a = pd.Series(np.random.random(10))
a
#generated an indexed array of random numbers


0    0.078090
1    0.983637
2    0.998613
3    0.812912
4    0.389391
5    0.898661
6    0.287520
7    0.990569
8    0.075254
9    0.419254
dtype: float64

In [75]:
a = a*10
a

0    0.780905
1    9.836367
2    9.986126
3    8.129122
4    3.893910
5    8.986611
6    2.875203
7    9.905689
8    0.752537
9    4.192540
dtype: float64

In [76]:
a = pd.Series(np.random.random(10)),index=['a','b','c','d','e','f','g','h','i','j']

SyntaxError: cannot assign to function call (<ipython-input-76-c3307fda5f74>, line 1)

In [77]:
#DATAFRAME

colnames = ['Column1','Column2','Column3','Column4','Column5']

df = pd.DataFrame(np.random.random((10,5)), columns=colnames)

df

Column1   Column2   Column3   Column4   Column5
0  0.042598  0.604250  0.981381  0.815422  0.832699
1  0.620916  0.595448  0.022575  0.362657  0.286553
2  0.058164  0.777569  0.346261  0.170911  0.077066
3  0.098531  0.804683  0.696053  0.444258  0.901609
4  0.906258  0.557205  0.995644  0.449786  0.732549
5  0.662892  0.515806  0.304127  0.374109  0.391534
6  0.103601  0.971379  0.025009  0.335553  0.079754
7  0.427994  0.633671  0.928579  0.763690  0.263068
8  0.193176  0.291835  0.918618  0.040566  0.807026
9  0.316953  0.180739  0.439722  0.920070  0.818002

In [78]:
np.random.random((10,10))

array([[0.34945126, 0.44070933, 0.30383087, 0.66918928, 0.09694844,
        0.99862774, 0.27289386, 0.04807721, 0.81294128, 0.69029542],
       [0.08755375, 0.10631071, 0.84167758, 0.4955757 , 0.96625603,
        0.36414844, 0.83593846, 0.05494718, 0.75682914, 0.06213874],
       [0.02274568, 0.62069116, 0.8193215 , 0.21067579, 0.04209079,
        0.72550967, 0.53552423, 0.3883944 , 0.48108887, 0.89083854],
       [0.29440341, 0.46854109, 0.1312245 , 0.49058944, 0.05341495,
        0.56326904, 0.8267615 , 0.0898673 , 0.1411915 , 0.0358785 ],
       [0.94105406, 0.99037625, 0.92834234, 0.26566239, 0.88825012,
        0.97864541, 0.4410287 , 0.9873585 , 0.84127574, 0.39523571],
       [0.41446807, 0.89398728, 0.72181214, 0.51228169, 0.29057438,
        0.91877637, 0.82676245, 0.71099482, 0.37904969, 0.96200436],
       [0.61065033, 0.22914884, 0.50420411, 0.56553347, 0.68897232,
        0.1192178 , 0.42572654, 0.52826768, 0.22250418, 0.93737612],
       [0.41594993, 0.88855254, 0.3481068

In [82]:
#TURN INTO DATAFRAME
df=pd.DataFrame(np.random.random((10,10)))
print(df)
#bekommt row and colums index

          0         1         2         3         4         5         6  \
0  0.495514  0.060375  0.354176  0.880173  0.245852  0.398253  0.991738   
1  0.827842  0.790021  0.661000  0.075192  0.573068  0.408565  0.668403   
2  0.003325  0.873125  0.549737  0.679978  0.792072  0.680106  0.848340   
3  0.610370  0.438205  0.730760  0.256713  0.041473  0.769259  0.994133   
4  0.234358  0.882540  0.675102  0.957963  0.483915  0.827397  0.610000   
5  0.954224  0.653716  0.644868  0.178107  0.223995  0.577968  0.082123   
6  0.568435  0.796743  0.814401  0.326276  0.949112  0.754641  0.219838   
7  0.012327  0.362564  0.664504  0.853014  0.932627  0.833643  0.586182   
8  0.330710  0.922514  0.918558  0.377706  0.327841  0.780896  0.654875   
9  0.325778  0.145114  0.609936  0.430327  0.554312  0.823227  0.842527   

          7         8         9  
0  0.614467  0.462247  0.354766  
1  0.250507  0.156877  0.919774  
2  0.765070  0.242808  0.508341  
3  0.901542  0.639581  0.880979  
4  0

In [91]:
colnames=[]
for i in range (len(df)):
              colnames.append('Columns' + str (i))


In [88]:
df_col=pd.DataFrame(np.random.random((10,10)), columns=colnames)
print(df_col)

   Columns0  Columns1  Columns2  Columns3  Columns4  Columns5  Columns6  \
0  0.801156  0.559332  0.574291  0.551097  0.914630  0.789606  0.363628   
1  0.062832  0.327376  0.605855  0.462142  0.622455  0.718132  0.270681   
2  0.040191  0.144167  0.496275  0.212787  0.194053  0.785379  0.176372   
3  0.452297  0.906591  0.789737  0.587881  0.015648  0.497249  0.034800   
4  0.765288  0.835445  0.360350  0.522623  0.518568  0.425020  0.115186   
5  0.412513  0.444627  0.057837  0.976447  0.198780  0.914776  0.029364   
6  0.227792  0.477593  0.981841  0.444484  0.531315  0.407000  0.986097   
7  0.145509  0.979708  0.568953  0.871335  0.789162  0.430949  0.823670   
8  0.011872  0.889685  0.063361  0.495570  0.239548  0.565404  0.596378   
9  0.941796  0.324410  0.039840  0.098503  0.372251  0.615705  0.350822   

   Columns7  Columns8  Columns9  
0  0.014060  0.464095  0.707457  
1  0.363741  0.659373  0.848107  
2  0.463453  0.871660  0.371867  
3  0.684141  0.509256  0.663503  
4  0

In [89]:
#After naming colums I can use thm to address the data
df_col['Columns0']

0    0.801156
1    0.062832
2    0.040191
3    0.452297
4    0.765288
5    0.412513
6    0.227792
7    0.145509
8    0.011872
9    0.941796
Name: Columns0, dtype: float64

In [92]:
#COMMAND HEAD TAIL
df_col.head()
#default is 5 first rows

Columns0  Columns1  Columns2  Columns3  Columns4  Columns5  Columns6  \
0  0.801156  0.559332  0.574291  0.551097  0.914630  0.789606  0.363628   
1  0.062832  0.327376  0.605855  0.462142  0.622455  0.718132  0.270681   
2  0.040191  0.144167  0.496275  0.212787  0.194053  0.785379  0.176372   
3  0.452297  0.906591  0.789737  0.587881  0.015648  0.497249  0.034800   
4  0.765288  0.835445  0.360350  0.522623  0.518568  0.425020  0.115186   

   Columns7  Columns8  Columns9  
0  0.014060  0.464095  0.707457  
1  0.363741  0.659373  0.848107  
2  0.463453  0.871660  0.371867  
3  0.684141  0.509256  0.663503  
4  0.541413  0.639792  0.638374

In [93]:
df_col.head(2) #erste 2 Reihen


Columns0  Columns1  Columns2  Columns3  Columns4  Columns5  Columns6  \
0  0.801156  0.559332  0.574291  0.551097  0.914630  0.789606  0.363628   
1  0.062832  0.327376  0.605855  0.462142  0.622455  0.718132  0.270681   

   Columns7  Columns8  Columns9  
0  0.014060  0.464095  0.707457  
1  0.363741  0.659373  0.848107

In [94]:
df_col.tail(2) #letzten 2 reihen

Columns0  Columns1  Columns2  Columns3  Columns4  Columns5  Columns6  \
8  0.011872  0.889685  0.063361  0.495570  0.239548  0.565404  0.596378   
9  0.941796  0.324410  0.039840  0.098503  0.372251  0.615705  0.350822   

   Columns7  Columns8  Columns9  
8  0.614548  0.869569  0.746695  
9  0.106602  0.211861  0.117676

In [95]:
df_col['Columns1'].head(3)
#erste 3 reihen der Column1

0    0.559332
1    0.327376
2    0.144167
Name: Columns1, dtype: float64

In [99]:
df_col['Columns2'][9]

0.039840072478027455

In [100]:
# Converting Other Data Structures to DataFrames
lst = [208500, 181500, 223500, 140000, 250000, 143000, 307000, 200000, 129900, 118000]

price_df = pd.DataFrame(lst, columns=['SalePrice'])

price_df

SalePrice
0     208500
1     181500
2     223500
3     140000
4     250000
5     143000
6     307000
7     200000
8     129900
9     118000

In [102]:
#TURN DICT IN TO DATAFRAME

house_dict = {'Baker House': [7420, 'BrkSide', 1939, 5, 118000],
              'Beazley House': [14115, 'Mitchel', 1993, 5, 143000],
              'Dominguez House': [14260, 'NoRidge', 2000, 8, 250000],
              'Hamilton House': [6120, 'OldTown', 1931, 7, 129900],
              'James House': [11250, 'CollgCr', 2001, 7, 223500],
              'Martinez House': [9600, 'Veenker', 1976, 6, 181500],
              'Roberts House': [9550, 'Crawfor', 1915, 7, 140000],
              'Smith House': [8450, 'CollgCr', 2003, 7, 208500],
              'Snyder House': [10084, 'Somerst', 2004, 8, 307000],
              'Zuckerman House': [10382, 'NWAmes', 1973, 7, 200000]}
pd.DataFrame(house_dict)


Baker House Beazley House Dominguez House Hamilton House James House  \
0        7420         14115           14260           6120       11250   
1     BrkSide       Mitchel         NoRidge        OldTown     CollgCr   
2        1939          1993            2000           1931        2001   
3           5             5               8              7           7   
4      118000        143000          250000         129900      223500   

  Martinez House Roberts House Smith House Snyder House Zuckerman House  
0           9600          9550        8450        10084           10382  
1        Veenker       Crawfor     CollgCr      Somerst          NWAmes  
2           1976          1915        2003         2004            1973  
3              6             7           7            8               7  
4         181500        140000      208500       307000          200000

In [108]:
pd.DataFrame.from_dict(house_dict, orient='index')

0        1     2  3       4
Baker House       7420  BrkSide  1939  5  118000
Beazley House    14115  Mitchel  1993  5  143000
Dominguez House  14260  NoRidge  2000  8  250000
Hamilton House    6120  OldTown  1931  7  129900
James House      11250  CollgCr  2001  7  223500
Martinez House    9600  Veenker  1976  6  181500
Roberts House     9550  Crawfor  1915  7  140000
Smith House       8450  CollgCr  2003  7  208500
Snyder House     10084  Somerst  2004  8  307000
Zuckerman House  10382   NWAmes  1973  7  200000

In [110]:
df_col.mean()

Columns0    0.386125
Columns1    0.588893
Columns2    0.453834
Columns3    0.522287
Columns4    0.439641
Columns5    0.614922
Columns6    0.374700
Columns7    0.509493
Columns8    0.615082
Columns9    0.527903
dtype: float64

In [112]:
df_col.mean(axis=0)#spalte

Columns0    0.386125
Columns1    0.588893
Columns2    0.453834
Columns3    0.522287
Columns4    0.439641
Columns5    0.614922
Columns6    0.374700
Columns7    0.509493
Columns8    0.615082
Columns9    0.527903
dtype: float64

In [113]:
df_col.mean(axis=1) #zeile

0    0.573935
1    0.494069
2    0.375620
3    0.514110
4    0.536206
5    0.532289
6    0.530718
7    0.648722
8    0.509263
9    0.317947
dtype: float64

In [118]:
#Subsetting and Filtering in Pandas
animals = pd.read_csv('/Users/spitzer/Desktop/IronHack/SleepInMammals.csv')
animals

Species of animal  Body Weight (kg)  Brain Weight (g)  \
0   African giant pouched rat             1.000              6.60   
1              Asian elephant          2547.000           4603.00   
2                      Baboon            10.550            179.50   
3               Big brown bat             0.023              0.30   
4             Brazilian tapir           160.000            169.00   
5                         Cat             3.300             25.60   
6                  Chimpanzee            52.160            440.00   
7                  Chinchilla             0.425              6.40   
8                         Cow           465.000            423.00   
9       Eastern American mole             0.075              1.20   
10                    Echidna             3.000             25.00   
11          European hedgehog             0.785              3.50   
12                     Galago             0.200              5.00   
13                       Goat            27.660            115.00   
14             Golden hamster             0.120              1.00   
15                  Gray seal            85.000            325.00   
16            Ground squirrel             0.101              4.00   
17                 Guinea pig             1.040              5.50   
18                      Horse           521.000            655.00   
19  Lesser short-tailed shrew             0.005              0.14   
20           Little brown bat             0.010              0.25   
21                      Human            62.000           1320.00   
22                      Mouse             0.023              0.40   
23                 Musk shrew             0.048              0.33   
24        N. American opossum             1.700              6.30   
25      Nine-banded armadillo             3.500             10.80   
26                 Owl monkey             0.480             15.50   
27               Patas monkey            10.000            115.00   
28                 Phanlanger             1.620             11.40   
29                        Pig           192.000            180.00   
30                     Rabbit             2.500             12.10   
31                        Rat             0.280              1.90   
32                    Red fox             4.235             50.40   
33              Rhesus monkey             6.800            179.00   
34                      Sheep            55.500            175.00   
35                     Tenrec             0.900              2.60   
36                 Tree hyrax             2.000             12.30   
37                 Tree shrew             0.104              2.50   
38                     Vervet             4.190             58.00   
39              Water opossum             3.500              3.90   

    Slow wave sleep (hrs/day)  Paradoxical sleep (hrs/day)  \
0                         6.3                          2.0   
1                         2.1                          1.8   
2                         9.1                          0.7   
3                        15.8                          3.9   
4                         5.2                          1.0   
5                        10.9                          3.6   
6                         8.3                          1.4   
7                        11.0                          1.5   
8                         3.2                          0.7   
9                         6.3                          2.1   
10                        8.6                          0.0   
11                        6.6                          4.1   
12                        9.5                          1.2   
13                        3.3                          0.5   
14                       11.0                          3.4   
15                        4.7                          1.5   
16                       10.4                          3.4   
17                        7.4                          0.8   
18  

In [119]:
animals.index.values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [126]:
#Selecting Columns
animals['Body Weight (kg)']

0        1.000
1     2547.000
2       10.550
3        0.023
4      160.000
5        3.300
6       52.160
7        0.425
8      465.000
9        0.075
10       3.000
11       0.785
12       0.200
13      27.660
14       0.120
15      85.000
16       0.101
17       1.040
18     521.000
19       0.005
20       0.010
21      62.000
22       0.023
23       0.048
24       1.700
25       3.500
26       0.480
27      10.000
28       1.620
29     192.000
30       2.500
31       0.280
32       4.235
33       6.800
34      55.500
35       0.900
36       2.000
37       0.104
38       4.190
39       3.500
Name: Body Weight (kg), dtype: float64

In [134]:
#Selecting Rows
animals[11:20]

Species of animal  Body Weight (kg)  Brain Weight (g)  \
11          European hedgehog             0.785              3.50   
12                     Galago             0.200              5.00   
13                       Goat            27.660            115.00   
14             Golden hamster             0.120              1.00   
15                  Gray seal            85.000            325.00   
16            Ground squirrel             0.101              4.00   
17                 Guinea pig             1.040              5.50   
18                      Horse           521.000            655.00   
19  Lesser short-tailed shrew             0.005              0.14   

    Slow wave sleep (hrs/day)  Paradoxical sleep (hrs/day)  \
11                        6.6                          4.1   
12                        9.5                          1.2   
13                        3.3                          0.5   
14                       11.0                          3.4   
15                        4.7                          1.5   
16                       10.4                          3.4   
17                        7.4                          0.8   
18                        2.1                          0.8   
19                        7.7                          1.4   

    Total sleep (hrs/day)  Maximum life span (years)  Gestation time (days)  \
11                   10.7                        6.0                   42.0   
12                   10.7                       10.4                  120.0   
13                    3.8                       20.0                  148.0   
14                   14.4                        3.9                   16.0   
15                    6.2                       41.0                  310.0   
16                   13.8                        9.0                   28.0   
17                    8.2                        7.6                   68.0   
18                    2.9                       46.0                  336.0   
19                    9.1                        2.6                   21.5   

    Predation index  Sleep exposure index  Overall danger index  
11                2                     2                     2  
12                2                     2                     2  
13                5                     5                     5  
14                3                     1                     2  
15                1                     3                     1  
16                5                     1                     3  
17                5                     3                     4  
18                5                     5                     5  
19                5                     2                     4

In [137]:
#SUBSETTING USING FUNCTIONS
#.loc is primarily label based. With .loc we perform subsetting using the name of the column
#.iloc is primarily integer based. With .iloc we perform subsetting using the integer position of the column


In [142]:
animals.iloc[[0,2,4],[0,1]]#Zeilen mit Index 0,2,4 Spalten mit Index 0 und 1

Species of animal  Body Weight (kg)
0  African giant pouched rat              1.00
2                     Baboon             10.55
4            Brazilian tapir            160.00

In [143]:
#FILTERING
animals[animals.Body Weight (kg) < 2]



SyntaxError: invalid syntax (<ipython-input-143-6d1445f207ff>, line 2)