In [6]:
names = ["john","paul","ringo","george"]

In [7]:
for i in names:
    print (i)
    if i == "ringo":
        break

john
paul
ringo


In [11]:
#loop macht 3er Schritte
for x in range (1,21,3):
    print (x)

1
4
7
10
13
16
19


In [12]:
#break befehl unterbricht loop
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    break
  print(x)

apple


In [13]:
#A nested loop is a loop inside a loop.
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, y) 

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry


In [16]:
#continue überspringt wert
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    continue
  print(x)


apple
cherry


In [5]:
#create list of 80 random elements with values 0-100
import random
sample_list_1=(random.sample(range(101), k=80))
print (sample_list_1)

[26, 20, 69, 33, 38, 0, 87, 89, 75, 40, 59, 23, 48, 53, 51, 96, 18, 52, 44, 41, 88, 99, 19, 73, 65, 95, 86, 77, 58, 8, 27, 32, 54, 3, 11, 4, 31, 78, 61, 5, 16, 12, 82, 13, 83, 17, 100, 7, 2, 10, 14, 42, 66, 98, 9, 35, 81, 21, 71, 29, 50, 85, 70, 72, 25, 63, 1, 37, 6, 39, 90, 45, 80, 47, 68, 36, 74, 91, 60, 57]


In [10]:
import random
random.randint(10, 11)

11

In [16]:
def hello_func():
    print("hello Function")

hello_func()
hello_func()
hello_func()
hello_func()

hello Function
hello Function
hello Function
hello Function


In [60]:
import random

def hello_func(greeting = "hi", name = "you") :
    return "{}, {}".format(greeting, name).upper()
    
print(hello_func())


HI, YOU


In [62]:
def student_info(*args, **kwargs):
    print(args)
    print(kwarg)

In [12]:
#dictonary key value pair
dict = {"cat": "meow", "cow":"mooh", "dog":"bark"}
x = dict["cat"]
print(x)

dict["bird"] ="zirp"
print(dict)

for k,v in dict.items():
    print(k+": "+v)

meow
{'cat': 'meow', 'cow': 'mooh', 'dog': 'bark', 'bird': 'zirp'}
cat: meow
cow: mooh
dog: bark
bird: zirp


In [6]:
myDict = {"name": "John", "country": "Norway"}
mySeparator = "TEST"

x = ", ".join(myDict.values())

print(x)


John, Norway


In [1]:
import numpy as np

In [5]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


In [8]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [17]:
message = 'How does this work?'
translated = '' #cipher text is stored in this variable
i = len(message) - 1

while i >= 0:
   translated = translated + message[i]
   i = i - 1
print('The cipher text is : ', translated)

The cipher text is :  ?krow siht seod woH


In [23]:
def encrypt(text,s):
result = ""
   # transverse the plain text
   for i in range(len(text)):
      char = text[i]
      # Encrypt uppercase characters in plain text
      
      if (char.isupper()):
         result += chr((ord(char) + s-65) % 26 + 65)
      # Encrypt lowercase characters in plain text
      else:
            result += chr((ord(char) + s - 97) % 26 + 97)
      return result
#check the above function
text = "CEASER CIPHER DEMO"
s = 4

print "Plain Text : " + text
print "Shift pattern : " + str(s)
print "Cipher: " + encrypt(text,s)

IndentationError: expected an indented block (<ipython-input-23-77fc53ce950e>, line 2)

In [2]:
#list comprehnsion
square=
print(square)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [1]:
import numpy as np

In [7]:
a=np.random.random((2,3))

array([[0.70999591, 0.17467466, 0.3007959 ],
       [0.47181181, 0.67001562, 0.22250329]])

In [9]:
a

array([[0.70999591, 0.17467466, 0.3007959 ],
       [0.47181181, 0.67001562, 0.22250329]])

In [10]:
a.shape

(2, 3)

In [12]:
a.size #two by three items is 6

6

In [14]:
a[0, 0] # element links oben

0.709995907254416

In [13]:
a [:,0] #hole first column

array([0.70999591, 0.47181181])

In [15]:
a[0,:] #hole first row

array([0.70999591, 0.17467466, 0.3007959 ])

In [18]:
np.random.random((2,3,5)) #3 dimensons: 2 depth / 3 columns / 5 rows

array([[[0.72705427, 0.88748976, 0.92034427, 0.82088818, 0.55002869],
        [0.7779625 , 0.13730653, 0.35114947, 0.34864345, 0.10887537],
        [0.08354085, 0.3562651 , 0.26825779, 0.07240365, 0.49767794]],

       [[0.92438818, 0.91510996, 0.93053889, 0.18144351, 0.83939823],
        [0.46366597, 0.37424037, 0.70944893, 0.21204728, 0.97774461],
        [0.70876304, 0.84201784, 0.50799983, 0.3978107 , 0.06324905]]])

In [20]:
b=np.random.random((2,3,5))
b

array([[[0.68247865, 0.20852647, 0.22112528, 0.65543431, 0.37505715],
        [0.31897464, 0.74235637, 0.08851318, 0.49493185, 0.75224304],
        [0.65626143, 0.68850065, 0.33461817, 0.33999101, 0.43618597]],

       [[0.86783736, 0.81682547, 0.16298816, 0.84439209, 0.37695437],
        [0.55356392, 0.17803441, 0.04035824, 0.67137878, 0.35845933],
        [0.02485719, 0.28495691, 0.21195664, 0.7883084 , 0.12776154]]])

In [21]:
b[0,0,0]

0.6824786539861356

In [23]:
b[0,2,:]#vorderste Matrix, komplette 3. Zeile,

array([0.65626143, 0.68850065, 0.33461817, 0.33999101, 0.43618597])

In [24]:
b[0,:,2]#vorderste Matrix komplette 3. Spalte

array([0.22112528, 0.08851318, 0.33461817])

In [25]:
#mutabe ich kann eine einzelne Zeile ändern
a[0,0,0]=5
a

array([[[5.        , 0.1589745 , 0.98210184, 0.75706021, 0.84765762],
        [0.54656323, 0.79365949, 0.77907511, 0.95757385, 0.70630361],
        [0.64564338, 0.46662405, 0.87795464, 0.67144808, 0.15875208]],

       [[0.82263695, 0.37617004, 0.69097118, 0.78922332, 0.17354848],
        [0.30052125, 0.05225526, 0.49345902, 0.85788907, 0.43201703],
        [0.09310094, 0.08965939, 0.36447655, 0.51059496, 0.75908949]]])

In [26]:
#insert list into array
mylist=['cat','dog']
np.array(mylist)

array(['cat', 'dog'], dtype='<U3')

In [1]:
import numpy as np

In [2]:
atoms = np.array([[0., 0., 0.],
                  [3., 3., 3.],
                  [2., 8., 7.]]
                 )

In [3]:
atoms

array([[0., 0., 0.],
       [3., 3., 3.],
       [2., 8., 7.]])

In [4]:
masses = np.array([1., 1., 5.])

In [8]:
atoms = atoms + [1.,2.,3.]
atoms

array([[ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 6., 13., 13.]])

In [19]:
riddle = np.array([[ 533.,  502.,  530.,  591.,  552.,  563.,  508.,  581.,  570.,  557.,  510.,  303.,  355.,  389.,  306.,  598.,  540.,  526.,  585.,  599.,  505.,  547.,  569.,  566.,  580.,  564.,  531.,  573.],
       [ 512.,  522.,  540.,  510.,  541.,  544.,  521.,  567.,  324.,  388.,  384.,  495.,  457.,  469.,  485.,  300.,  426.,  410.,  584.,  545.,  518.,  591.,  518.,  536.,  508.,  556.,  595.,  560.],
       [ 545.,  584.,  521.,  552.,  589.,  583.,  314.,  301.,  461.,  473.,  436.,  469.,  478.,  440.,  449.,  431.,  461.,  461.,  322.,  319.,  592.,  522.,  554.,  569.,  593.,  502.,  551.,  514.],
       [ 576.,  517.,  538.,  588.,  550.,  331.,  529.,  532.,  470.,  469.,  471.,  461.,  426.,  400.,  450.,  462.,  422.,  430.,  454.,  487.,  398.,  529.,  584.,  567.,  594.,  522.,  530.,  506.],
       [ 542.,  582.,  520.,  525.,  319.,  575.,  543.,  481.,  413.,  474.,  408.,  446.,  433.,  465.,  409.,  448.,  407.,  401.,  485.,  434.,  403.,  360.,  525.,  523.,  581.,  528.,  555.,  567.],
       [ 533.,  588.,  569.,  383.,  581.,  541.,  558.,  448.,  411.,  425.,  403.,  463.,  423.,  457.,  493.,  472.,  460.,  470.,  444.,  418.,  498.,  426.,  340.,  577.,  556.,  544.,  560.,  589.],
       [ 576.,  552.,  550.,  365.,  587.,  543.,  575.,  586.,  425.,  430.,  493.,  488.,  446.,  460.,  447.,  493.,  404.,  414.,  444.,  430.,  417.,  449.,  317.,  538.,  559.,  596.,  513.,  553.],
       [ 567.,  574.,  374.,  513.,  578.,  593.,  539.,  555.,  512.,  407.,  435.,  483.,  458.,  456.,  462.,  433.,  497.,  465.,  459.,  400.,  445.,  436.,  456.,  356.,  547.,  526.,  508.,  573.],
       [ 537.,  515.,  398.,  576.,  525.,  530.,  529.,  584.,  544.,  513.,  450.,  420.,  426.,  489.,  441.,  432.,  427.,  444.,  482.,  415.,  486.,  472.,  466.,  320.,  501.,  535.,  592.,  580.],
       [ 539.,  542.,  304.,  522.,  565.,  500.,  559.,  530.,  554.,  520.,  526.,  594.,  423.,  472.,  477.,  468.,  428.,  374.,  343.,  332.,  379.,  419.,  477.,  354.,  557.,  554.,  554.,  550.],
       [ 544.,  383.,  567.,  520.,  575.,  372.,  393.,  528.,  546.,  571.,  531.,  538.,  548.,  540.,  566.,  355.,  387.,  407.,  471.,  332.,  352.,  347.,  369.,  494.,  394.,  566.,  590.,  521.],
       [ 590.,  326.,  524.,  327.,  357.,  501.,  559.,  348.,  566.,  516.,  522.,  505.,  502.,  501.,  363.,  445.,  442.,  398.,  329.,  548.,  591.,  512.,  595.,  358.,  344.,  571.,  519.,  543.],
       [ 571.,  362.,  322.,  544.,  251.,  223.,  523.,  544.,  355.,  542.,  597.,  587.,  571.,  322.,  446.,  377.,  343.,  108.,  509.,  573.,  136.,  584.,  672.,  367.,  349.,  564.,  543.,  520.],
       [ 585.,  312.,  225.,  228.,  435.,  484.,  215.,  536.,  336.,  522.,  529.,  557.,  375.,  455.,  350.,  371.,  108.,  523.,  507.,  218.,  298.,  221.,  292.,  244.,  242.,  294.,  556.,  573.],
       [ 552.,  232.,  444.,  458.,  454.,  435.,  234.,  564.,  503.,  365.,  589.,  555.,  303.,  394.,  582.,  364.,  507.,  258.,  299.,  258.,  219.,  291.,  269.,  269.,  243.,  230.,  281.,  536.],
       [ 279.,  522.,  453.,  406.,  419.,  487.,  444.,  514.,  283.,  398.,  521.,  352.,  487.,  309.,  347.,  108.,  214.,  236.,  602.,  261.,  221.,  200.,  292.,  235.,  261.,  236.,  292.,  540.],
       [ 227.,  460.,  430.,  405.,  451.,  108.,  544.,  454.,  409.,  379.,  505.,  595.,  314.,  317.,  325.,  108.,  236.,  279.,  270.,  234.,  226.,  553.,  215.,  219.,  246.,  622.,  540.,  577.],
       [ 595.,  218.,  209.,  456.,  108.,  584.,  549.,  576.,  450.,  401.,  491.,  515.,  321.,  654.,  697.,  267.,  276.,  249.,  531.,  651.,  606.,  558.,  604.,  693.,  594.,  570.,  560.,  523.],
       [ 524.,  564.,  433.,  400.,  108.,  516.,  575.,  413.,  662.,  648.,  666.,  470.,  579.,  488.,  641.,  210.,  204.,  553.,  541.,  648.,  238.,  656.,  230.,  642.,  549.,  599.,  598.,  500.],
       [ 524.,  596.,  549.,  439.,  108.,  108.,  437.,  691.,  693.,  671.,  659.,  628.,  420.,  494.,  581.,  282.,  246.,  506.,  611.,  612.,  227.,  670.,  275.,  691.,  634.,  461.,  597.,  553.],
       [ 573.,  577.,  595.,  436.,  468.,  108.,  479.,  679.,  686.,  686.,  678.,  627.,  435.,  586.,  515.,  297.,  264.,  263.,  679.,  648.,  521.,  570.,  609.,  601.,  687.,  481.,  574.,  509.],
       [ 501.,  544.,  508.,  539.,  430.,  499.,  108.,  474.,  656.,  669.,  601.,  462.,  108.,  108.,  108.,  502.,  232.,  685.,  687.,  201.,  437.,  569.,  549.,  576.,  558.,  409.,  516.,  584.],
       [ 527.,  515.,  584.,  581.,  505.,  411.,  462.,  489.,  465.,  454.,  406.,  108.,  108.,  347.,  307.,  262.,  576.,  580.,  282.,  262.,  240.,  295.,  276.,  210.,  214.,  280.,  277.,  509.],
       [ 537.,  562.,  565.,  573.,  559.,  500.,  466.,  464.,  410.,  404.,  108.,  108.,  108.,  108.,  108.,  287.,  543.,  521.,  686.,  659.,  261.,  278.,  266.,  276.,  293.,  288.,  554.,  541.],
       [ 586.,  596.,  509.,  579.,  530.,  508.,  579.,  480.,  439.,  629.,  631.,  458.,  488.,  416.,  429.,  477.,  487.,  535.,  564.,  546.,  538.,  529.,  596.,  412.,  500.,  559.,  508.,  596.],
       [ 536.,  578.,  502.,  522.,  531.,  525.,  587.,  580.,  501.,  487.,  439.,  432.,  478.,  443.,  405.,  548.,  533.,  439.,  486.,  415.,  476.,  417.,  472.,  541.,  528.,  595.,  531.,  549.],
       [ 548.,  562.,  550.,  561.,  584.,  598.,  572.,  584.,  581.,  544.,  577.,  591.,  548.,  530.,  512.,  552.,  587.,  511.,  577.,  565.,  591.,  560.,  565.,  595.,  544.,  556.,  585.,  520.]])

In [21]:
riddle

array([[533., 502., 530., 591., 552., 563., 508., 581., 570., 557., 510.,
        303., 355., 389., 306., 598., 540., 526., 585., 599., 505., 547.,
        569., 566., 580., 564., 531., 573.],
       [512., 522., 540., 510., 541., 544., 521., 567., 324., 388., 384.,
        495., 457., 469., 485., 300., 426., 410., 584., 545., 518., 591.,
        518., 536., 508., 556., 595., 560.],
       [545., 584., 521., 552., 589., 583., 314., 301., 461., 473., 436.,
        469., 478., 440., 449., 431., 461., 461., 322., 319., 592., 522.,
        554., 569., 593., 502., 551., 514.],
       [576., 517., 538., 588., 550., 331., 529., 532., 470., 469., 471.,
        461., 426., 400., 450., 462., 422., 430., 454., 487., 398., 529.,
        584., 567., 594., 522., 530., 506.],
       [542., 582., 520., 525., 319., 575., 543., 481., 413., 474., 408.,
        446., 433., 465., 409., 448., 407., 401., 485., 434., 403., 360.,
        525., 523., 581., 528., 555., 567.],
       [533., 588., 569., 383., 581

In [24]:
print(riddle.shape)
print(riddle.size)

(27, 28)
756


In [30]:
riddle[:,-1]

array([573., 560., 514., 506., 567., 589., 553., 573., 580., 550., 521.,
       543., 520., 573., 536., 540., 577., 523., 500., 553., 509., 584.,
       509., 541., 596., 549., 520.])

In [36]:

for x in riddle: 
    if x >=200 and  x<= 300:
        riddle [x]=0
    elif x>=300 and  x<=400:
        riddle [x]=40
    elif x>=400 and  x<=500:
        riddle [x]=156
    elif x>=500 and  x<=600:
        riddle [x]=220
riddle

TypeError: 'tuple' object is not callable