In [6]:
names = ["john","paul","ringo","george"]

In [7]:
for i in names:
    print (i)
    if i == "ringo":
        break

john
paul
ringo


In [11]:
#loop macht 3er Schritte
for x in range (1,21,3):
    print (x)

1
4
7
10
13
16
19


In [12]:
#break befehl unterbricht loop
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    break
  print(x)

apple


In [13]:
#A nested loop is a loop inside a loop.
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, y) 

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry


In [16]:
#continue überspringt wert
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    continue
  print(x)


apple
cherry


In [5]:
#create list of 80 random elements with values 0-100
import random
sample_list_1=(random.sample(range(101), k=80))
print (sample_list_1)

[26, 20, 69, 33, 38, 0, 87, 89, 75, 40, 59, 23, 48, 53, 51, 96, 18, 52, 44, 41, 88, 99, 19, 73, 65, 95, 86, 77, 58, 8, 27, 32, 54, 3, 11, 4, 31, 78, 61, 5, 16, 12, 82, 13, 83, 17, 100, 7, 2, 10, 14, 42, 66, 98, 9, 35, 81, 21, 71, 29, 50, 85, 70, 72, 25, 63, 1, 37, 6, 39, 90, 45, 80, 47, 68, 36, 74, 91, 60, 57]


In [10]:
import random
random.randint(10, 11)

11

In [16]:
def hello_func():
    print("hello Function")

hello_func()
hello_func()
hello_func()
hello_func()

hello Function
hello Function
hello Function
hello Function


In [60]:
import random

def hello_func(greeting = "hi", name = "you") :
    return "{}, {}".format(greeting, name).upper()
    
print(hello_func())


HI, YOU


In [62]:
def student_info(*args, **kwargs):
    print(args)
    print(kwarg)

In [12]:
#dictonary key value pair
dict = {"cat": "meow", "cow":"mooh", "dog":"bark"}
x = dict["cat"]
print(x)

dict["bird"] ="zirp"
print(dict)

for k,v in dict.items():
    print(k+": "+v)

meow
{'cat': 'meow', 'cow': 'mooh', 'dog': 'bark', 'bird': 'zirp'}
cat: meow
cow: mooh
dog: bark
bird: zirp


In [6]:
myDict = {"name": "John", "country": "Norway"}
mySeparator = "TEST"

x = ", ".join(myDict.values())

print(x)


John, Norway


In [1]:
import numpy as np

In [5]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


In [8]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [17]:
message = 'How does this work?'
translated = '' #cipher text is stored in this variable
i = len(message) - 1

while i >= 0:
   translated = translated + message[i]
   i = i - 1
print('The cipher text is : ', translated)

The cipher text is :  ?krow siht seod woH


In [23]:
def encrypt(text,s):
result = ""
   # transverse the plain text
   for i in range(len(text)):
      char = text[i]
      # Encrypt uppercase characters in plain text
      
      if (char.isupper()):
         result += chr((ord(char) + s-65) % 26 + 65)
      # Encrypt lowercase characters in plain text
      else:
            result += chr((ord(char) + s - 97) % 26 + 97)
      return result
#check the above function
text = "CEASER CIPHER DEMO"
s = 4

print "Plain Text : " + text
print "Shift pattern : " + str(s)
print "Cipher: " + encrypt(text,s)

IndentationError: expected an indented block (<ipython-input-23-77fc53ce950e>, line 2)

In [2]:
#list comprehnsion
square=[x*x for x in range(10)]
print(square)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
