In [3]:
names = ["john","paul","ringo","george"]

In [4]:
for i in names:
    print (i)
    if i == "ringo":
        break

john
paul
ringo


In [5]:
#loop macht 3er Schritte
for x in range (1,21,3):
    print (x)

1
4
7
10
13
16
19


In [6]:
#break befehl unterbricht loop
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    break
  print(x)

apple


In [7]:
#A nested loop is a loop inside a loop.
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, y) 

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry


In [8]:
#continue überspringt wert
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    continue
  print(x)


apple
cherry


In [9]:
#create list of 80 random elements with values 0-100
import random
sample_list_1=(random.sample(range(101), k=80))
print (sample_list_1)

[84, 33, 23, 1, 44, 66, 70, 38, 31, 36, 12, 89, 39, 69, 96, 21, 46, 63, 0, 13, 6, 100, 77, 8, 58, 93, 76, 29, 32, 56, 40, 90, 67, 24, 94, 49, 48, 64, 75, 54, 88, 28, 16, 78, 86, 22, 97, 19, 99, 53, 62, 18, 80, 20, 30, 37, 11, 74, 35, 3, 50, 61, 55, 68, 17, 95, 79, 98, 2, 83, 5, 87, 85, 57, 59, 15, 27, 34, 4, 60]


In [10]:
import random
random.randint(10, 11)

10

In [11]:
def hello_func():
    print("hello Function")

hello_func()
hello_func()
hello_func()
hello_func()

hello Function
hello Function
hello Function
hello Function


In [12]:
import random

def hello_func(greeting = "hi", name = "you") :
    return "{}, {}".format(greeting, name).upper()
    
print(hello_func())


HI, YOU


In [13]:
def student_info(*args, **kwargs):
    print(args)
    print(kwarg)

In [14]:
#dictonary key value pair
dict = {"cat": "meow", "cow":"mooh", "dog":"bark"}
x = dict["cat"]
print(x)

dict["bird"] ="zirp"
print(dict)

for k,v in dict.items():
    print(k+": "+v)

meow
{'cat': 'meow', 'cow': 'mooh', 'dog': 'bark', 'bird': 'zirp'}
cat: meow
cow: mooh
dog: bark
bird: zirp


In [15]:
myDict = {"name": "John", "country": "Norway"}
mySeparator = "TEST"

x = ", ".join(myDict.values())

print(x)


John, Norway


In [16]:
import numpy as np

In [17]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


In [18]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [20]:
message = 'How does this work?'
translated = '' #cipher text is stored in this variable
i = len(message) - 1

while i >= 0:
   translated = translated + message[i]
   i = i - 1
print('The cipher text is : ', translated)

The cipher text is :  ?krow siht seod woH


In [21]:
def encrypt(text,s):
result = ""
   # transverse the plain text
   for i in range(len(text)):
      char = text[i]
      # Encrypt uppercase characters in plain text
      
      if (char.isupper()):
         result += chr((ord(char) + s-65) % 26 + 65)
      # Encrypt lowercase characters in plain text
      else:
            result += chr((ord(char) + s - 97) % 26 + 97)
      return result
#check the above function
text = "CEASER CIPHER DEMO"
s = 4

print "Plain Text : " + text
print "Shift pattern : " + str(s)
print "Cipher: " + encrypt(text,s)

IndentationError: expected an indented block (<ipython-input-21-77fc53ce950e>, line 2)

In [ ]:
#list comprehnsion
square=
print(square)

In [23]:
import numpy as np

In [24]:
a=np.random.random((2,3))

In [25]:
a

array([[0.00711434, 0.01613151, 0.170539  ],
       [0.62967321, 0.43648852, 0.5433418 ]])

In [26]:
a.shape

(2, 3)

In [27]:
a.size #two by three items is 6

6

In [28]:
a[0, 0] # element links oben

0.0071143357237223315

In [29]:
a [:,0] #hole first column

array([0.00711434, 0.62967321])

In [30]:
a[0,:] #hole first row

array([0.00711434, 0.01613151, 0.170539  ])

In [31]:
np.random.random((2,3,5)) #3 dimensons: 2 depth / 3 columns / 5 rows

array([[[0.03474619, 0.6407788 , 0.79723381, 0.57268447, 0.51062382],
        [0.09640925, 0.30676413, 0.79504163, 0.55670414, 0.9285344 ],
        [0.67239878, 0.03020509, 0.32714086, 0.14975026, 0.86263021]],

       [[0.02909728, 0.81314075, 0.68681486, 0.02192829, 0.01769043],
        [0.25531275, 0.37218867, 0.8244451 , 0.62678242, 0.70772964],
        [0.56702296, 0.74600682, 0.32333266, 0.20127352, 0.93388457]]])

In [32]:
b=np.random.random((2,3,5))
b

array([[[0.3012421 , 0.50597416, 0.75989096, 0.97537364, 0.85513257],
        [0.73207502, 0.9797952 , 0.53746343, 0.76546102, 0.69817599],
        [0.12589537, 0.62258934, 0.95659582, 0.80897047, 0.0452021 ]],

       [[0.93392817, 0.0104043 , 0.22007246, 0.6270459 , 0.06877639],
        [0.30343447, 0.0244144 , 0.60235848, 0.15477219, 0.37802477],
        [0.78602222, 0.37841686, 0.28776075, 0.61531766, 0.72860003]]])

In [53]:
b*10 #smart way to have random numbers between 0 and 10 - 10 not included

array([[[3.01242102, 5.05974164, 7.59890955, 9.75373638, 8.5513257 ],
        [7.3207502 , 9.797952  , 5.37463428, 7.65461021, 6.98175993],
        [1.25895371, 6.22589341, 9.56595822, 8.0897047 , 0.452021  ]],

       [[9.33928168, 0.10404295, 2.20072462, 6.27045897, 0.68776394],
        [3.03434467, 0.244144  , 6.02358478, 1.54772186, 3.78024774],
        [7.86022217, 3.78416859, 2.8776075 , 6.15317663, 7.28600027]]])

In [33]:
b[0,0,0]

0.30124210222100367

In [34]:
b[0,2,:]#vorderste Matrix, komplette 3. Zeile,

array([0.12589537, 0.62258934, 0.95659582, 0.80897047, 0.0452021 ])

In [35]:
b[0,:,2]#vorderste Matrix komplette 3. Spalte

array([0.75989096, 0.53746343, 0.95659582])

In [36]:
#mutabe ich kann eine einzelne Zeile ändern
a[0,0,0]=5
a

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [37]:
#insert list into array
mylist=['cat','dog']
np.array(mylist)

array(['cat', 'dog'], dtype='<U3')

In [38]:
#DIFFRENCE nump.add" vs "+"

In [56]:
first=[1,2,3]
second=[4,5,6]
print(first+second) #joins two lists
print (np.add(first,second))#addiert Element für Element

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [ ]:
import numpy as np

In [39]:
atoms = np.array([[0., 0., 0.],
                  [3., 3., 3.],
                  [2., 8., 7.]]
                 )

In [40]:
atoms

array([[0., 0., 0.],
       [3., 3., 3.],
       [2., 8., 7.]])

In [41]:
masses = np.array([1., 1., 5.])

In [42]:
atoms = atoms + [1.,2.,3.]
atoms

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 3., 10., 10.]])

In [43]:
riddle = np.array([[ 533.,  502.,  530.,  591.,  552.,  563.,  508.,  581.,  570.,  557.,  510.,  303.,  355.,  389.,  306.,  598.,  540.,  526.,  585.,  599.,  505.,  547.,  569.,  566.,  580.,  564.,  531.,  573.],
       [ 512.,  522.,  540.,  510.,  541.,  544.,  521.,  567.,  324.,  388.,  384.,  495.,  457.,  469.,  485.,  300.,  426.,  410.,  584.,  545.,  518.,  591.,  518.,  536.,  508.,  556.,  595.,  560.],
       [ 545.,  584.,  521.,  552.,  589.,  583.,  314.,  301.,  461.,  473.,  436.,  469.,  478.,  440.,  449.,  431.,  461.,  461.,  322.,  319.,  592.,  522.,  554.,  569.,  593.,  502.,  551.,  514.],
       [ 576.,  517.,  538.,  588.,  550.,  331.,  529.,  532.,  470.,  469.,  471.,  461.,  426.,  400.,  450.,  462.,  422.,  430.,  454.,  487.,  398.,  529.,  584.,  567.,  594.,  522.,  530.,  506.],
       [ 542.,  582.,  520.,  525.,  319.,  575.,  543.,  481.,  413.,  474.,  408.,  446.,  433.,  465.,  409.,  448.,  407.,  401.,  485.,  434.,  403.,  360.,  525.,  523.,  581.,  528.,  555.,  567.],
       [ 533.,  588.,  569.,  383.,  581.,  541.,  558.,  448.,  411.,  425.,  403.,  463.,  423.,  457.,  493.,  472.,  460.,  470.,  444.,  418.,  498.,  426.,  340.,  577.,  556.,  544.,  560.,  589.],
       [ 576.,  552.,  550.,  365.,  587.,  543.,  575.,  586.,  425.,  430.,  493.,  488.,  446.,  460.,  447.,  493.,  404.,  414.,  444.,  430.,  417.,  449.,  317.,  538.,  559.,  596.,  513.,  553.],
       [ 567.,  574.,  374.,  513.,  578.,  593.,  539.,  555.,  512.,  407.,  435.,  483.,  458.,  456.,  462.,  433.,  497.,  465.,  459.,  400.,  445.,  436.,  456.,  356.,  547.,  526.,  508.,  573.],
       [ 537.,  515.,  398.,  576.,  525.,  530.,  529.,  584.,  544.,  513.,  450.,  420.,  426.,  489.,  441.,  432.,  427.,  444.,  482.,  415.,  486.,  472.,  466.,  320.,  501.,  535.,  592.,  580.],
       [ 539.,  542.,  304.,  522.,  565.,  500.,  559.,  530.,  554.,  520.,  526.,  594.,  423.,  472.,  477.,  468.,  428.,  374.,  343.,  332.,  379.,  419.,  477.,  354.,  557.,  554.,  554.,  550.],
       [ 544.,  383.,  567.,  520.,  575.,  372.,  393.,  528.,  546.,  571.,  531.,  538.,  548.,  540.,  566.,  355.,  387.,  407.,  471.,  332.,  352.,  347.,  369.,  494.,  394.,  566.,  590.,  521.],
       [ 590.,  326.,  524.,  327.,  357.,  501.,  559.,  348.,  566.,  516.,  522.,  505.,  502.,  501.,  363.,  445.,  442.,  398.,  329.,  548.,  591.,  512.,  595.,  358.,  344.,  571.,  519.,  543.],
       [ 571.,  362.,  322.,  544.,  251.,  223.,  523.,  544.,  355.,  542.,  597.,  587.,  571.,  322.,  446.,  377.,  343.,  108.,  509.,  573.,  136.,  584.,  672.,  367.,  349.,  564.,  543.,  520.],
       [ 585.,  312.,  225.,  228.,  435.,  484.,  215.,  536.,  336.,  522.,  529.,  557.,  375.,  455.,  350.,  371.,  108.,  523.,  507.,  218.,  298.,  221.,  292.,  244.,  242.,  294.,  556.,  573.],
       [ 552.,  232.,  444.,  458.,  454.,  435.,  234.,  564.,  503.,  365.,  589.,  555.,  303.,  394.,  582.,  364.,  507.,  258.,  299.,  258.,  219.,  291.,  269.,  269.,  243.,  230.,  281.,  536.],
       [ 279.,  522.,  453.,  406.,  419.,  487.,  444.,  514.,  283.,  398.,  521.,  352.,  487.,  309.,  347.,  108.,  214.,  236.,  602.,  261.,  221.,  200.,  292.,  235.,  261.,  236.,  292.,  540.],
       [ 227.,  460.,  430.,  405.,  451.,  108.,  544.,  454.,  409.,  379.,  505.,  595.,  314.,  317.,  325.,  108.,  236.,  279.,  270.,  234.,  226.,  553.,  215.,  219.,  246.,  622.,  540.,  577.],
       [ 595.,  218.,  209.,  456.,  108.,  584.,  549.,  576.,  450.,  401.,  491.,  515.,  321.,  654.,  697.,  267.,  276.,  249.,  531.,  651.,  606.,  558.,  604.,  693.,  594.,  570.,  560.,  523.],
       [ 524.,  564.,  433.,  400.,  108.,  516.,  575.,  413.,  662.,  648.,  666.,  470.,  579.,  488.,  641.,  210.,  204.,  553.,  541.,  648.,  238.,  656.,  230.,  642.,  549.,  599.,  598.,  500.],
       [ 524.,  596.,  549.,  439.,  108.,  108.,  437.,  691.,  693.,  671.,  659.,  628.,  420.,  494.,  581.,  282.,  246.,  506.,  611.,  612.,  227.,  670.,  275.,  691.,  634.,  461.,  597.,  553.],
       [ 573.,  577.,  595.,  436.,  468.,  108.,  479.,  679.,  686.,  686.,  678.,  627.,  435.,  586.,  515.,  297.,  264.,  263.,  679.,  648.,  521.,  570.,  609.,  601.,  687.,  481.,  574.,  509.],
       [ 501.,  544.,  508.,  539.,  430.,  499.,  108.,  474.,  656.,  669.,  601.,  462.,  108.,  108.,  108.,  502.,  232.,  685.,  687.,  201.,  437.,  569.,  549.,  576.,  558.,  409.,  516.,  584.],
       [ 527.,  515.,  584.,  581.,  505.,  411.,  462.,  489.,  465.,  454.,  406.,  108.,  108.,  347.,  307.,  262.,  576.,  580.,  282.,  262.,  240.,  295.,  276.,  210.,  214.,  280.,  277.,  509.],
       [ 537.,  562.,  565.,  573.,  559.,  500.,  466.,  464.,  410.,  404.,  108.,  108.,  108.,  108.,  108.,  287.,  543.,  521.,  686.,  659.,  261.,  278.,  266.,  276.,  293.,  288.,  554.,  541.],
       [ 586.,  596.,  509.,  579.,  530.,  508.,  579.,  480.,  439.,  629.,  631.,  458.,  488.,  416.,  429.,  477.,  487.,  535.,  564.,  546.,  538.,  529.,  596.,  412.,  500.,  559.,  508.,  596.],
       [ 536.,  578.,  502.,  522.,  531.,  525.,  587.,  580.,  501.,  487.,  439.,  432.,  478.,  443.,  405.,  548.,  533.,  439.,  486.,  415.,  476.,  417.,  472.,  541.,  528.,  595.,  531.,  549.],
       [ 548.,  562.,  550.,  561.,  584.,  598.,  572.,  584.,  581.,  544.,  577.,  591.,  548.,  530.,  512.,  552.,  587.,  511.,  577.,  565.,  591.,  560.,  565.,  595.,  544.,  556.,  585.,  520.]])

In [44]:
riddle

array([[533., 502., 530., 591., 552., 563., 508., 581., 570., 557., 510.,
        303., 355., 389., 306., 598., 540., 526., 585., 599., 505., 547.,
        569., 566., 580., 564., 531., 573.],
       [512., 522., 540., 510., 541., 544., 521., 567., 324., 388., 384.,
        495., 457., 469., 485., 300., 426., 410., 584., 545., 518., 591.,
        518., 536., 508., 556., 595., 560.],
       [545., 584., 521., 552., 589., 583., 314., 301., 461., 473., 436.,
        469., 478., 440., 449., 431., 461., 461., 322., 319., 592., 522.,
        554., 569., 593., 502., 551., 514.],
       [576., 517., 538., 588., 550., 331., 529., 532., 470., 469., 471.,
        461., 426., 400., 450., 462., 422., 430., 454., 487., 398., 529.,
        584., 567., 594., 522., 530., 506.],
       [542., 582., 520., 525., 319., 575., 543., 481., 413., 474., 408.,
        446., 433., 465., 409., 448., 407., 401., 485., 434., 403., 360.,
        525., 523., 581., 528., 555., 567.],
       [533., 588., 569., 383., 581

In [45]:
print(riddle.shape)
print(riddle.size)

(27, 28)
756


In [46]:
riddle[:,-1]

array([573., 560., 514., 506., 567., 589., 553., 573., 580., 550., 521.,
       543., 520., 573., 536., 540., 577., 523., 500., 553., 509., 584.,
       509., 541., 596., 549., 520.])

In [50]:
print(riddle)

[[533. 502. 530. 591. 552. 563. 508. 581. 570. 557. 510. 303. 355. 389.
  306. 598. 540. 526. 585. 599. 505. 547. 569. 566. 580. 564. 531. 573.]
 [512. 522. 540. 510. 541. 544. 521. 567. 324. 388. 384. 495. 457. 469.
  485. 300. 426. 410. 584. 545. 518. 591. 518. 536. 508. 556. 595. 560.]
 [545. 584. 521. 552. 589. 583. 314. 301. 461. 473. 436. 469. 478. 440.
  449. 431. 461. 461. 322. 319. 592. 522. 554. 569. 593. 502. 551. 514.]
 [576. 517. 538. 588. 550. 331. 529. 532. 470. 469. 471. 461. 426. 400.
  450. 462. 422. 430. 454. 487. 398. 529. 584. 567. 594. 522. 530. 506.]
 [542. 582. 520. 525. 319. 575. 543. 481. 413. 474. 408. 446. 433. 465.
  409. 448. 407. 401. 485. 434. 403. 360. 525. 523. 581. 528. 555. 567.]
 [533. 588. 569. 383. 581. 541. 558. 448. 411. 425. 403. 463. 423. 457.
  493. 472. 460. 470. 444. 418. 498. 426. 340. 577. 556. 544. 560. 589.]
 [576. 552. 550. 365. 587. 543. 575. 586. 425. 430. 493. 488. 446. 460.
  447. 493. 404. 414. 444. 430. 417. 449. 317. 538. 559. 5

In [58]:

for x in len(riddle): 
    if riddle[x] >=200 and  riddle[x]<= 300:
        riddle [x]=0
    elif riddle[x]>=300 and  riddle[x]<=400:
        riddle [x]=40
    elif riddle[x]>=400 and  riddle[x]<=500:
        riddle [x]=156
    elif riddle[x]>=500 and  riddle[x]<=600:
        riddle [x]=220
riddle

TypeError: 'int' object is not iterable