# Working with Numpy

Numpy is the numerical python package, with a lot of mathematical capabilities. Before we can use it, we need to first import the package. We will import it under the name np such that we can afterwards refer to it by this short name.

In [5]:
# your code here
import numpy as np

In the cell below, generate two 2x3 array with all elements equal to 1 - assign one of the arrays to the variable a and the other one to b. Add the two arrays. What do you get?

In [19]:
# your code here
a= np.full((2, 3), 1)
b= np.full((2, 3), 1)

print("Array a:\n", a)
print("Array b:\n", b)

print("Array a+b:\n", a+b)

Array a:
 [[1 1 1]
 [1 1 1]]
Array b:
 [[1 1 1]
 [1 1 1]]
Array a+b:
 [[2 2 2]
 [2 2 2]]


Now generate another array c which is a 3x2 array with all elements equal to 1. Are you able to add a and c? Why or why not?

In [20]:
# your code here
c= np.full((3, 2), 1)
print(c)
a+c
#When operating on two arrays, NumPy compares their shapes element-wise. 
#It starts with the trailing dimensions and works its way forward. 
#Two dimensions are compatible when they are equal, or one of them is 1
#ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

[[1 1]
 [1 1]
 [1 1]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Transpose c so that it has the same structure of a (i.e. become a 2x3 array). Assign the transposed array to variable "d". Are you able to add a and d?

In [24]:
# your code here
d=np.transpose(c)
print("Array d transposed form c:\n",d)
#print("Array a+d:\n",a+d)
print("Array a+d:\n",np.add(a,d))
print("ANSWER: Yes, I am able to add a and d")

Array d transposed form c:
 [[1 1 1]
 [1 1 1]]
Array a+d:
 [[2 2 2]
 [2 2 2]]
ANSWER: Yes, I am able to add a and d


Which combination of arrays are you able to multiply with each other? Why?

In [9]:
# your code here
#When operating on two arrays, NumPy compares their shapes element-wise. 
#It starts with the trailing dimensions and works its way forward. 
#Two dimensions are compatible when they are equal, or one of them is 1

Create a list which contains the numbers from 0 to 10. Square the list elementwise using numpy functions.

In [29]:
# your code here
#a=[x+1 for x in range (-1,10)]
a=np.arange(0,11)
print("List 0 to 1:\n",a)
print("List above squared:\n",np.square(a))



List 0 to 1:
 [ 0  1  2  3  4  5  6  7  8  9 10]
List above squared:
 [  0   1   4   9  16  25  36  49  64  81 100]


Create a numpy array of size 10x10 which has random numbers between 0 and 100 on the main diagonal and zeros otherwise.

In [31]:
e=np.full ((10,10),0)


In [36]:
#SMART SOLUTION
np.fill_diagonal(e,(np.random.random(10))*100)
print(e)
#MY FIRST SOLUTION
#for f in range(len(e)):
#    for g in range (len(e)):
#        if f==g:
#           #e[f,g]=np.random.random_integers(0,100)
#            e[f,g]=np.random.randint(1, 101)
#       else:
#           continue
#e

[[30  0  0  0  0  0  0  0  0  0]
 [ 0 56  0  0  0  0  0  0  0  0]
 [ 0  0 28  0  0  0  0  0  0  0]
 [ 0  0  0 69  0  0  0  0  0  0]
 [ 0  0  0  0 25  0  0  0  0  0]
 [ 0  0  0  0  0 38  0  0  0  0]
 [ 0  0  0  0  0  0 41  0  0  0]
 [ 0  0  0  0  0  0  0 19  0  0]
 [ 0  0  0  0  0  0  0  0 89  0]
 [ 0  0  0  0  0  0  0  0  0 32]]
