## Challenge A: Password Validator

#### Description
Your job is to create a simple password validation function, as seen on many websites.

The rules for a valid password are as follows:

There needs to be at least 1 uppercase letter.
There needs to be at least 1 lowercase letter.
There needs to be at least 1 number.
The password needs to be at least 8 characters long.

*You are permitted to use any methods to validate the password.*

In [205]:
import pandas as pd
import numpy as np
from functools import reduce
import re
import random
import string

In [208]:
#STREAMLINING CRITERA CHECK
'''CRITERIA DICTIONARY'''
crit_dict={'upper':False,'lower':False,'number':False,'minlength':False}
crit_list=['(1)hold 1 uppercase letter','(2)hold 1 lowercase letter','(3)hold 1 digit','(4)minimum length of 8 characters']
tries=0 #counts efforts to enter password
'''---------------------------------'''

'''USER INPUTS PASSWORD'''
def enter_pwd(x):
    tries=+1 # counts efforts to enter password
    print(f'CREATE PASSWORD\n---\nHi {x}, enter the password you‘d like to go with\nYour password needs to meet these {len(crit_dict.items())} criteria:\n')
    for i in range(4):
        print(f'{crit_list[i]}')
    print('\n---')     
    pwd_string=input()
    return pwd_string
'''---------------------------------'''

'''CHECKING CRITERIA'''

def crit_check(pwd_string):
    print('---\n...checking criteria...\n---')
        #number check
    if any(i.isdigit() for i in pwd_string):
        crit_dict['number']=True
        #length check
    if len(pwd_string) >= 8:
        crit_dict['minlength'] = True
    for i in pwd_string:
        #uppercase check
        if i.isupper():
            crit_dict['upper'] = True 
        #lowercase check
        if i.islower():
             crit_dict['lower'] = True
    return crit_dict
'''---------------------------------'''

'''FEEDBACK FOR USER'''

def crit_feedback(crit_dict):
    print(crit_dict)
    if reduce(lambda a,b: a + b, crit_dict.values())==len(crit_dict.items()):
        return print('---\nBIGLY SUCCESS!\nWhat a tremendous password')
    else:
        return print('---\nFail! Your password is weak and so are you!\nSAD!')
    
'''---------------------------------'''
'''---PROGRAMM---'''
username='[UserName]'
pwd_string=enter_pwd('[UserName]')
crit_dict=crit_check(pwd_string)
feedback=crit_feedback(crit_dict)

CREATE PASSWORD
---
Hi [UserName], enter the password you‘d like to go with
Your password needs to meet these 4 criteria:

(1)hold 1 uppercase letter
(2)hold 1 lowercase letter
(3)hold 1 digit
(4)minimum length of 8 characters

---
thomas23_E
---
...checking criteria...
---
{'upper': True, 'lower': True, 'number': True, 'minlength': True}
---
BIGLY SUCCESS!
What a tremendous password


In [216]:
#WITH REGULAR EXPRESSIONS
import re

password=input()

def checking(x):
    check='valid'
    if len(x)<=8:
        print ('password too short')
        check='invalid'
    if re.search('[0-9]', x) == None:
        print ('password lacks a number')
        check='invalid'
    if re.search('[a-z]', x) == None:
        print ('lacking lower case')
        check='invalid'
    if re.search('[A-Z]', x) == None:
        print ('lacking upper case')
        check='invalid'
    if check=='invalid':
        print('Password failed to process, try again')
    else:
            return 'SUCESS! Your password meets all criteria'
checking(password)


Thomas Spitzer 1982


'SUCESS! Your password meets all criteria'

## Challenge B: Credit Card Validator

#### Description

Your task is to write a program which reads credit card number prints the validation result ‘Valid’ or ‘Invalid’.

A valid credit card has following features:

- It should start with 4, 5 or 6
- It should have exactly 16 digits
- It should only consist of digits (0-9)
- It may have digits in groups of 4 and separated by one hyphen "-"
- It should NOT use any other separator like ‘ ’,‘_’, etc.
- It should NOT have 4 or more consecutive repeated digits

Valid Credit Card Numbers:
1. 4263525778615786
2. 5535535535559555
3. 6344-2389-7542-9163

Invalid Credit Card Numbers:
1. 42536258796157867       
2. 66266666626662666       
3. 5122-2368-7954 -3214   
4. 44244x4424442444       
5. 0525362587961578

In [ ]:
# your code here 
card_num=str(input())
def check (x)
if (x[0] in ['4','5,'6']) & (len(x.replace('-',''))==16) & (set.findall([\W]', x')) in [set()]
             
check(card_num)

## Challenge C: Multiplication Table

#### Description
    
Your task, is to create a function which returns a **NxN multiplication table**, of size N provided as a function argument.

for example, when given size is 3:

1 2 3

2 4 6

3 6 9

So for the given example, the return value should be: [[1,2,3],[2,4,6],[3,6,9]]

In [32]:
size=int(input())
x = np.ones((size,size))

for i in range(size):
    x[i]= np.arange(1,(size+1))*(i+1)
                    
print (x)

3
[[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]]


## Challenge D: ID Assignment

#### Description

a) You work in a company with 100 people - to start, please create a list of people ranging from Person 1 to Person 100. For company purposes, each of these people is identified with a Personal ID, which is a combination of 2 uppercase letters and a random number of 5 digits. For each person, generate a random ID, and store it in a dictionary alongside their name (for example ('Person 5': 'AB73648')). Then sort the dictionary according to the values of their Personal IDs.

b) One month later, your company changes the ID format for every employee - from now on, every person will have an ID that consists of only letters. In order to convert them, every letter in the employee ID should be replaced by the corresponding uppercase letter in the alphabeth. Please write a function that accomplishes this change

In [186]:
# CREATE DICTIONARY


#CREAT DICTONARY WITH PERSON NUMBERS AS KEYS and AN ID FROM CAPITAL LETTERS AND DIGITS AS IDs
#Person 1 - Person 100 List
empl_list=[f'Person'+' '+str(i) for i in range(1,101)]
#Create IDs
char_set = set([string.ascii_uppercase[np.random.randint(25)]+ string.ascii_uppercase[np.random.randint(25)]for x in range(100)])
numbers_list=[random.randint(10000, 99999) for x in range (len(empl_list))]
id_list=[(lambda a,b: f'{a}{b}')(a,b) for (a,b) in zip(char_set,numbers_list)]
#Create dictionary
empl_dict={}
empl_dict=dict(zip(empl_list,id_list))
#Sort by value
empl_dict=dict(sorted(empl_dict.items(), key=lambda x: x[1]))
print(empl_dict)
print(len(empl_dict))

{'Person 87': 'AA15364', 'Person 14': 'AC51449', 'Person 89': 'AD92157', 'Person 84': 'AS17445', 'Person 9': 'BD41828', 'Person 8': 'CT65245', 'Person 53': 'CV32014', 'Person 48': 'CW13763', 'Person 71': 'CY42370', 'Person 10': 'DA42344', 'Person 52': 'DF66244', 'Person 7': 'DL65992', 'Person 23': 'DT91305', 'Person 58': 'EF15516', 'Person 92': 'EI45464', 'Person 22': 'ES54935', 'Person 86': 'EU48520', 'Person 70': 'FD16655', 'Person 25': 'FI61769', 'Person 16': 'FM77735', 'Person 6': 'GH68829', 'Person 11': 'GI27273', 'Person 50': 'GX93057', 'Person 91': 'HO89658', 'Person 72': 'HV17794', 'Person 46': 'II56926', 'Person 38': 'IL35370', 'Person 80': 'IS49674', 'Person 24': 'IT40386', 'Person 21': 'JH46521', 'Person 34': 'JI36609', 'Person 82': 'JR12333', 'Person 1': 'JY46049', 'Person 74': 'KA75484', 'Person 88': 'KU46643', 'Person 56': 'KX45640', 'Person 27': 'LB67412', 'Person 67': 'LO76775', 'Person 41': 'MC33717', 'Person 30': 'MI85335', 'Person 73': 'MN42656', 'Person 3': 'MP11750

In [183]:
#CHANGE ID: Now only 4 letters. Existing 2 letters should remain.
value_list=list(empl_dict.values())
new_id_value=[value_list[i][0:2]+string.ascii_uppercase[np.random.randint(25)]+string.ascii_uppercase[np.random.randint(25)] for i in range(len(value_list))]
print(new_id_value)

['ABXT', 'ACYX', 'AEQM', 'AFKB', 'AIKK', 'APGQ', 'BXYI', 'BYSU', 'CIFC', 'CVJO', 'CXVV', 'DGXA', 'DWNM', 'EDQH', 'ELEQ', 'EUEJ', 'FBRC', 'FLED', 'FMXX', 'FPMP', 'FWPD', 'GHVN', 'GJFG', 'GLDO', 'GPSU', 'GTYB', 'HGFQ', 'IPHV', 'IYRH', 'JALS', 'JMCV', 'JNUY', 'JPPJ', 'KEWC', 'KLHU', 'KPJQ', 'LDSU', 'LHHB', 'LIGP', 'LODD', 'LXLK', 'LYGA', 'MDAX', 'MGRI', 'MVSB', 'NAAH', 'NEWG', 'NLEI', 'NOYP', 'NPHO', 'NVLN', 'NXRM', 'OERY', 'OMGW', 'ORNT', 'OYAA', 'PBRI', 'PKDW', 'QGGU', 'QMLU', 'QSVI', 'RCMM', 'RHKH', 'ROEC', 'RUFO', 'SBUA', 'SJYC', 'SOGV', 'SQES', 'SRGY', 'SYBU', 'TMJW', 'TUHM', 'UCJO', 'UEOO', 'UMAW', 'UOSU', 'VHHF', 'VIIF', 'VJTW', 'VPXH', 'VUOE', 'WAWJ', 'WBRM', 'WDUI', 'WUFA', 'XDQJ', 'XFPN', 'XVEW', 'YJYP', 'YKCE', 'YRBA', 'YSOG']
93


In [195]:
for a,b in zip(empl_dict.keys(),new_id_value):
    empl_dict[a]=b
print(empl_dict)

{'Person 87': 'ABXT', 'Person 14': 'ACYX', 'Person 89': 'AEQM', 'Person 84': 'AFKB', 'Person 9': 'AIKK', 'Person 8': 'APGQ', 'Person 53': 'BXYI', 'Person 48': 'BYSU', 'Person 71': 'CIFC', 'Person 10': 'CVJO', 'Person 52': 'CXVV', 'Person 7': 'DGXA', 'Person 23': 'DWNM', 'Person 58': 'EDQH', 'Person 92': 'ELEQ', 'Person 22': 'EUEJ', 'Person 86': 'FBRC', 'Person 70': 'FLED', 'Person 25': 'FMXX', 'Person 16': 'FPMP', 'Person 6': 'FWPD', 'Person 11': 'GHVN', 'Person 50': 'GJFG', 'Person 91': 'GLDO', 'Person 72': 'GPSU', 'Person 46': 'GTYB', 'Person 38': 'HGFQ', 'Person 80': 'IPHV', 'Person 24': 'IYRH', 'Person 21': 'JALS', 'Person 34': 'JMCV', 'Person 82': 'JNUY', 'Person 1': 'JPPJ', 'Person 74': 'KEWC', 'Person 88': 'KLHU', 'Person 56': 'KPJQ', 'Person 27': 'LDSU', 'Person 67': 'LHHB', 'Person 41': 'LIGP', 'Person 30': 'LODD', 'Person 73': 'LXLK', 'Person 3': 'LYGA', 'Person 79': 'MDAX', 'Person 42': 'MGRI', 'Person 57': 'MVSB', 'Person 26': 'NAAH', 'Person 93': 'NEWG', 'Person 28': 'NLEI