## Challenge A: Password Validator

#### Description
Your job is to create a simple password validation function, as seen on many websites.

The rules for a valid password are as follows:

There needs to be at least 1 uppercase letter.
There needs to be at least 1 lowercase letter.
There needs to be at least 1 number.
The password needs to be at least 8 characters long.

*You are permitted to use any methods to validate the password.*

In [59]:
import pandas as pd
import numpy as np
from functools import reduce
import re
import random
import string

In [33]:
'''CRITERIA DICTIONARY'''
crit_dict={'upper':False,'lower':False,'number':False,'minlength':False}
crit_list=['(1)hold 1 uppercase letter','(2)hold 1 lowercase letter','(3)hold 1 digit','(4)minimum length of 8 characters']
tries=0 #counts efforts to enter password
'''---------------------------------'''

'''USER INPUTS PASSWORD'''
def enter_pwd(x):
    tries=+1 # counts efforts to enter password
    print(f'CREATE PASSWORD\n---\nHi {x}, enter the password you‘d like to go with\nYour password needs to meet these {len(crit_dict.items())} criteria:\n')
    for i in range(4):
        print(f'{crit_list[i]}')
    print('\n---')     
    pwd_string=input()
    return pwd_string
'''---------------------------------'''

'''CHECKING CRITERIA'''

def crit_check(pwd_string):
    print('---\n...checking criteria...\n---')
        #number check
    if any(i.isdigit() for i in pwd_string):
        crit_dict['number']=True
        #length check
    if len(pwd_string) >= 8:
        crit_dict['minlength'] = True
    for i in pwd_string:
        #uppercase check
        if i.isupper():
            crit_dict['upper'] = True 
        #lowercase check
        if i.islower():
             crit_dict['lower'] = True
    return crit_dict
'''---------------------------------'''

'''FEEDBACK FOR USER'''

def crit_feedback(crit_dict):
    print(crit_dict)
    if reduce(lambda a,b: a + b, crit_dict.values())==len(crit_dict.items()):
        return print('---\nBIGLY SUCCESS!\nWhat a tremendous password')
    else:
        return print('---\nFAIL! Your password is weak and so are you!\nSAD!')
    
'''---------------------------------'''
'''---PROGRAMM---'''
username='[UserName]'
pwd_string=enter_pwd('[UserName]')
crit_dict=crit_check(pwd_string)
feedback=crit_feedback(crit_dict)

CREATE PASSWORD
---
Hi [UserName], enter the password you‘d like to go with
Your password needs to meet these 4 criteria:

(1)hold 1 uppercase letter
(2)hold 1 lowercase letter
(3)hold 1 digit
(4)minimum length of 8 characters

---
Thomas25
---
...checking criteria...
---
{'upper': True, 'lower': True, 'number': True, 'minlength': True}
---
BIGLY SUCCESS!
What a tremendous password


## Challenge B: Credit Card Validator

#### Description

Your task is to write a program which reads credit card number prints the validation result ‘Valid’ or ‘Invalid’.

A valid credit card has following features:

- It should start with 4, 5 or 6
- It should have exactly 16 digits
- It should only consist of digits (0-9)
- It may have digits in groups of 4 and separated by one hyphen "-"
- It should NOT use any other separator like ‘ ’,‘_’, etc.
- It should NOT have 4 or more consecutive repeated digits

Valid Credit Card Numbers:
1. 4263525778615786
2. 5535535535559555
3. 6344-2389-7542-9163

Invalid Credit Card Numbers:
1. 42536258796157867       
2. 66266666626662666       
3. 5122-2368-7954 -3214   
4. 44244x4424442444       
5. 0525362587961578

In [ ]:
# your code here 
if (x[0] in ['4','5,'6']) & (len(x.replace('-',''))==16) & (set.findall([\W]', x')) in [set()]

## Challenge C: Multiplication Table

#### Description
    
Your task, is to create a function which returns a **NxN multiplication table**, of size N provided as a function argument.

for example, when given size is 3:

1 2 3

2 4 6

3 6 9

So for the given example, the return value should be: [[1,2,3],[2,4,6],[3,6,9]]

In [32]:
size=int(input())
x = np.ones((size,size))

for i in range(size):
    x[i]= np.arange(1,(size+1))*(i+1)
                    
print (x)

3
[[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]]


## Challenge D: ID Assignment

#### Description

a) You work in a company with 100 people - to start, please create a list of people ranging from Person 1 to Person 100. For company purposes, each of these people is identified with a Personal ID, which is a combination of 2 uppercase letters and a random number of 5 digits. For each person, generate a random ID, and store it in a dictionary alongside their name (for example ('Person 5': 'AB73648')). Then sort the dictionary according to the values of their Personal IDs.

b) One month later, your company changes the ID format for every employee - from now on, every person will have an ID that consists of only letters. In order to convert them, every letter in the employee ID should be replaced by the corresponding uppercase letter in the alphabeth. Please write a function that accomplishes this change

In [81]:
# your code here

#empl_dict['Person'+' '+str(i) for i in range(1,101)]='2'
#d[f'Person'+' '+str(i) for i in range(1,101)] = '2'
empl_dict={}
empl_list=[f'Person'+' '+str(i) for i in range(1,101)]
numbers_list=[random.randint(10000, 99999) for x in range (len(empl_list))]
print(numbers_list)
#CREAT SET OF RANDOM DOUBLE CHARACTERS
char_set = set([string.ascii_uppercase[np.random.randint(25)]+ string.ascii_uppercase[np.random.randint(25)]for x in range(100)])
print(char_set)

id_list=[(lambda a,b: f'{a}{b}')(a,b) for (a,b) in zip(char_set,numbers_list)]
print(id_list)


empl_dict=dict(zip(empl_list,id_list))
empl_dict

[12506, 83920, 15934, 22763, 99314, 86503, 40455, 33407, 60374, 71207, 19534, 26671, 47924, 22307, 46133, 66401, 34869, 76910, 36115, 55206, 13886, 27833, 53091, 59078, 12716, 42456, 69270, 47349, 72344, 27955, 43438, 53993, 56074, 76746, 56984, 55807, 81216, 97644, 90664, 91354, 86094, 79747, 85687, 20315, 39221, 47108, 96978, 72318, 27312, 95212, 66346, 73643, 13885, 95707, 41353, 55907, 78033, 46105, 33950, 15577, 33143, 52975, 40383, 41806, 46350, 38031, 79961, 85730, 63889, 11305, 26335, 21787, 89310, 63636, 46523, 13946, 49271, 26393, 17151, 12760, 16258, 66542, 87888, 40339, 37296, 61015, 55073, 31787, 18949, 30938, 53144, 60134, 47573, 40811, 57912, 18036, 71042, 87299, 41397, 59281]
{'VS', 'KM', 'VX', 'IB', 'TQ', 'YC', 'HN', 'WY', 'VY', 'LM', 'DU', 'HG', 'EM', 'WG', 'GB', 'VM', 'NN', 'KY', 'TJ', 'NH', 'WF', 'XQ', 'DC', 'WM', 'UJ', 'IQ', 'RA', 'JB', 'PD', 'IK', 'VQ', 'MC', 'SJ', 'DB', 'JC', 'DV', 'RO', 'FE', 'SN', 'XY', 'NC', 'WO', 'BS', 'XJ', 'OM', 'RL', 'VR', 'YE', 'DF', 'CR'

{'Person 1': 'VS12506',
 'Person 2': 'KM83920',
 'Person 3': 'VX15934',
 'Person 4': 'IB22763',
 'Person 5': 'TQ99314',
 'Person 6': 'YC86503',
 'Person 7': 'HN40455',
 'Person 8': 'WY33407',
 'Person 9': 'VY60374',
 'Person 10': 'LM71207',
 'Person 11': 'DU19534',
 'Person 12': 'HG26671',
 'Person 13': 'EM47924',
 'Person 14': 'WG22307',
 'Person 15': 'GB46133',
 'Person 16': 'VM66401',
 'Person 17': 'NN34869',
 'Person 18': 'KY76910',
 'Person 19': 'TJ36115',
 'Person 20': 'NH55206',
 'Person 21': 'WF13886',
 'Person 22': 'XQ27833',
 'Person 23': 'DC53091',
 'Person 24': 'WM59078',
 'Person 25': 'UJ12716',
 'Person 26': 'IQ42456',
 'Person 27': 'RA69270',
 'Person 28': 'JB47349',
 'Person 29': 'PD72344',
 'Person 30': 'IK27955',
 'Person 31': 'VQ43438',
 'Person 32': 'MC53993',
 'Person 33': 'SJ56074',
 'Person 34': 'DB76746',
 'Person 35': 'JC56984',
 'Person 36': 'DV55807',
 'Person 37': 'RO81216',
 'Person 38': 'FE97644',
 'Person 39': 'SN90664',
 'Person 40': 'XY91354',
 'Person 